version: "3"

services:
  backend:
    image: delivery/backend
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - DB_HOST
      - DB_PORT

  db:
    image: postgres:bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - ./db:/var/lib/postgresql/data
